#!/bin/bash

# Signup URL
signup_url="http://localhost:3001/signup"

# Array of user data as JSON
users=(
 '[
    {
        "username": "simonkannan",
        "email": "chopranidra@example.net",
        "first_name": "Bakhshi",
        "last_name": "Mangat",
        "hashed_password": "y(kaRFC8@v",
        "age": 31,
        "gender": "Male",
        "location": "Hapur",
        "score": 64,
        "openness": "Low",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Casual",
        "social_habits": "Outgoing",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "vkaur",
        "email": "vbabu@example.org",
        "first_name": "Maanav",
        "last_name": "Master",
        "hashed_password": "QD1DARse@*",
        "age": 38,
        "gender": "Male",
        "location": "Singrauli",
        "score": 76,
        "openness": "High",
        "interests": "Sports",
        "exp_qual": "Creative, Energetic",
        "relation_type": "Serious",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "ikbal79",
        "email": "jdoshi@example.net",
        "first_name": "Inaya",
        "last_name": "Bhattacharyya",
        "hashed_password": "Z2KUro5(%m",
        "age": 57,
        "gender": "Female",
        "location": "Jalgaon",
        "score": 63,
        "openness": "Medium",
        "interests": "Traveling",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Casual",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "tsamra",
        "email": "tchandra@example.com",
        "first_name": "Sai",
        "last_name": "Sant",
        "hashed_password": "Ce5)MwHpy%",
        "age": 49,
        "gender": "Female",
        "location": "Buxar",
        "score": 79,
        "openness": "High",
        "interests": "Traveling",
        "exp_qual": "Creative, Energetic",
        "relation_type": "Casual",
        "social_habits": "Unspecified",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "ckar",
        "email": "atisem@example.com",
        "first_name": "Dev",
        "last_name": "Bakshi",
        "hashed_password": "u^8obNbwmF",
        "age": 22,
        "gender": "Male",
        "location": "Katni",
        "score": 61,
        "openness": "High",
        "interests": "Traveling",
        "exp_qual": "Creative, Energetic",
        "relation_type": "Unspecified",
        "social_habits": "Outgoing",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "gguha",
        "email": "ikbalmital@example.com",
        "first_name": "Jhalak",
        "last_name": "Naik",
        "hashed_password": "km3&nHlB#j",
        "age": 23,
        "gender": "Female",
        "location": "Jorhat",
        "score": 67,
        "openness": "Medium",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Casual",
        "social_habits": "Outgoing",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "vrishtiranganathan",
        "email": "ishaan88@example.org",
        "first_name": "Jalsa",
        "last_name": "Sharma",
        "hashed_password": "b!44JYx_fd",
        "age": 44,
        "gender": "Female",
        "location": "Jamnagar",
        "score": 30,
        "openness": "Medium",
        "interests": "Reading",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Unspecified",
        "social_habits": "Introverted",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "balhaardeo",
        "email": "zinal74@example.net",
        "first_name": "Janaki",
        "last_name": "Goel",
        "hashed_password": "$eAUIvQ80X",
        "age": 59,
        "gender": "Female",
        "location": "Bharatpur",
        "score": 71,
        "openness": "Low",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Serious",
        "social_habits": "Introverted",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "jsaini",
        "email": "pathakgirik@example.net",
        "first_name": "Manan",
        "last_name": "Behl",
        "hashed_password": "YR*+5Uv!Uk",
        "age": 48,
        "gender": "Male",
        "location": "Etawah",
        "score": 89,
        "openness": "Medium",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Serious",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "veda38",
        "email": "jagatbasu@example.org",
        "first_name": "Pahal",
        "last_name": "Kanda",
        "hashed_password": "$f92BHaLYq",
        "age": 19,
        "gender": "Female",
        "location": "Bettiah",
        "score": 33,
        "openness": "Low",
        "interests": "Cooking",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Serious",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "murtyrachana",
        "email": "srivastavaadvik@example.net",
        "first_name": "Urmi",
        "last_name": "Devi",
        "hashed_password": "_Z@6NX7uSo",
        "age": 53,
        "gender": "Female",
        "location": "Tiruvottiyur",
        "score": 82,
        "openness": "Medium",
        "interests": "Cooking",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Casual",
        "social_habits": "Outgoing",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "owenkalita",
        "email": "jacob94@example.com",
        "first_name": "Rayaan",
        "last_name": "Doctor",
        "hashed_password": ")qy2UCCxm_",
        "age": 27,
        "gender": "Male",
        "location": "Hubli\u2013Dharwad",
        "score": 82,
        "openness": "High",
        "interests": "Sports",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Casual",
        "social_habits": "Unspecified",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "wnanda",
        "email": "qsoni@example.net",
        "first_name": "Girish",
        "last_name": "De",
        "hashed_password": "XyScKLEK#3",
        "age": 28,
        "gender": "Male",
        "location": "Phusro",
        "score": 44,
        "openness": "Low",
        "interests": "Traveling",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Serious",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "bajwatamanna",
        "email": "gaganbora@example.com",
        "first_name": "Ranveer",
        "last_name": "Ray",
        "hashed_password": "$2MqcWofbG",
        "age": 49,
        "gender": "Male",
        "location": "Khandwa",
        "score": 45,
        "openness": "Medium",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Unspecified",
        "social_habits": "Outgoing",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "gerakrishna",
        "email": "sdutt@example.org",
        "first_name": "Onveer",
        "last_name": "Basak",
        "hashed_password": "(hDTR&_r!9",
        "age": 58,
        "gender": "Male",
        "location": "Nagaon",
        "score": 82,
        "openness": "Low",
        "interests": "Reading",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Unspecified",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "azaan87",
        "email": "dayaladya@example.net",
        "first_name": "Harinakshi",
        "last_name": "Devi",
        "hashed_password": "%#VjWJKi#5",
        "age": 56,
        "gender": "Female",
        "location": "Secunderabad",
        "score": 45,
        "openness": "Neutral",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Unspecified",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "raviekaraj",
        "email": "purizarna@example.org",
        "first_name": "Siddharth",
        "last_name": "Kapadia",
        "hashed_password": "#7gGb(Ai0k",
        "age": 41,
        "gender": "Male",
        "location": "Sri Ganganagar",
        "score": 75,
        "openness": "High",
        "interests": "Cooking",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Unspecified",
        "social_habits": "Outgoing",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "gadeorinder",
        "email": "arin46@example.com",
        "first_name": "Lohit",
        "last_name": "Om",
        "hashed_password": "+X6D)O0ye^",
        "age": 58,
        "gender": "Male",
        "location": "Panchkula",
        "score": 77,
        "openness": "Medium",
        "interests": "Reading",
        "exp_qual": "Creative, Energetic",
        "relation_type": "Casual",
        "social_habits": "Unspecified",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "ekta89",
        "email": "wchada@example.com",
        "first_name": "Chaitaly",
        "last_name": "Panchal",
        "hashed_password": "$5SExchXmJ",
        "age": 45,
        "gender": "Female",
        "location": "Kolhapur",
        "score": 71,
        "openness": "Neutral",
        "interests": "Cooking",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Casual",
        "social_habits": "Outgoing",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "chanakya70",
        "email": "gnanda@example.org",
        "first_name": "Eta",
        "last_name": "Bahl",
        "hashed_password": "t^9DT5fZ*b",
        "age": 25,
        "gender": "Female",
        "location": "Gudivada",
        "score": 32,
        "openness": "High",
        "interests": "Sports",
        "exp_qual": "Creative, Energetic",
        "relation_type": "Serious",
        "social_habits": "Introverted",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "puriishwar",
        "email": "yatanvohra@example.org",
        "first_name": "Daksha",
        "last_name": "Krishnan",
        "hashed_password": "*rHcg1sRM3",
        "age": 45,
        "gender": "Female",
        "location": "Haridwar",
        "score": 85,
        "openness": "High",
        "interests": "Reading",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Unspecified",
        "social_habits": "Introverted",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/27364526/pexels-photo-27364526/free-photo-of-portrait.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        "username": "kbera",
        "email": "sbaral@example.org",
        "first_name": "George",
        "last_name": "Palan",
        "hashed_password": "#DRRRE4w)9",
        "age": 26,
        "gender": "Male",
        "location": "Bangalore",
        "score": 46,
        "openness": "Low",
        "interests": "Sports",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Casual",
        "social_habits": "Introverted",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "rattiomaja",
        "email": "edwinsanya@example.com",
        "first_name": "Faraj",
        "last_name": "Dhar",
        "hashed_password": "WX^c2L1wgg",
        "age": 56,
        "gender": "Male",
        "location": "Siliguri",
        "score": 36,
        "openness": "Neutral",
        "interests": "Traveling",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Serious",
        "social_habits": "Unspecified",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "korpalranveer",
        "email": "edhithanagarajan@example.org",
        "first_name": "Ishaan",
        "last_name": "Grover",
        "hashed_password": "F6SN9TAi@h",
        "age": 55,
        "gender": "Male",
        "location": "Begusarai",
        "score": 53,
        "openness": "Medium",
        "interests": "Sports",
        "exp_qual": "Adventurous, Open-minded",
        "relation_type": "Serious",
        "social_habits": "Unspecified",
        "past_relations": "Yes",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    },
    {
        "username": "inigam",
        "email": "wshetty@example.com",
        "first_name": "Tanay",
        "last_name": "Dasgupta",
        "hashed_password": "He18VVzCF(",
        "age": 22,
        "gender": "Male",
        "location": "Bhind",
        "score": 61,
        "openness": "Medium",
        "interests": "Music",
        "exp_qual": "Calm, Thoughtful",
        "relation_type": "Unspecified",
        "social_habits": "Outgoing",
        "past_relations": "No",
        "image_url": "https://images.pexels.com/photos/17715613/pexels-photo-17715613/free-photo-of-a-man-sitting-on-a-bench-with-his-hands-on-his-hips.jpeg"
    }
]'
)

# Loop through each user and send POST request
for user in "${users[@]}"; do
  curl -X POST "$signup_url" \
  -H "Content-Type: application/json" \
  -d "$user"

  echo "User signed up: $(echo $user | jq '.username')"
done
