apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.rusty_backend.repository }}:{{ .Values.image.rusty_backend.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret 
        volumeMounts:
            - name: certs-volume
              mountPath: /certs/client
              readOnly: true
            - name: backend-data
              mountPath: /var/rusty_backend_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: certs-volume
          persistentVolumeClaim:
            claimName: rustybackenddockercerts
        - name: backend-data
          persistentVolumeClaim:
            claimName: rustybackenddata
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
