apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SMTP_PASSWORD: {{ .Values.smtp.smtpPassword | b64enc | quote     }}
  OTP_SECRET: {{ .Values.otpSecret | b64enc | quote  }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote}}