apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SMTP_PASSWORD: {{ .Values.smtp.smtpPassword | b64enc | quote     }}
  OTP_SECRET: {{ .Values.otpSecret | b64enc | quote  }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote}}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{.Values.secrets.awsSecretAccessKey | b64enc | quote }}
  AWS_REGION: {{.Values.secrets.awsRegion | b64enc | quote }}