apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30100