name: Build and Push Docker Images

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Backend image
      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sidharthsingh7/rusty_backend

     
