//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize)]
#[sea_orm(table_name = "friend_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub girl_email_id: String,
    pub boy_email_id: String,
    pub flag: String,
    pub contest_score: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
