//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::avatar::Entity as Avatar;
pub use super::game_sessions::Entity as GameSessions;
pub use super::matches::Entity as Matches;
pub use super::pass_reset::Entity as PassReset;
pub use super::user_details::Entity as UserDetails;
pub use super::users::Entity as Users;
